server {
    listen 8443 ssl;
    server_name admin.local;

    ssl_certificate     /etc/nginx/certs/admin-selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/admin-selfsigned.key;

    # Maubot API and UI (Must be placed ABOVE the general /_matrix/ block)
    location /_matrix/maubot/ {
        proxy_pass http://maubot:29316;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
    }

    # Maubot log viewer websocket
    location /_matrix/maubot/v1/logs {
        proxy_pass http://maubot:29316;
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }


    # synapse-admin / ketesa UI
    location / {
        proxy_pass http://synapse-admin:8080;
        proxy_set_header Host $host;
    }

    # Synapse admin API
    location /_synapse/admin/ {
        proxy_pass http://synapse:8008;
        proxy_set_header Host $host;
    }

    # Synapse client-server API
    location /_matrix/ {
        proxy_pass http://synapse:8008;
        proxy_set_header Host $host;
    }
}
